sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - llvm-toolchain-precise-3.6
    - george-edison55-precise-backports
    # ^ for cmake
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.6
    - gettext
    - libboost1.55-dev
    - gdb
    - cmake-data
    - cmake
script:
  - $CXX --version

  - echo "Unit Tests"
  - cd test && ./test.sh

  - echo "Libintl Validation Tests"
  - cd ../test_libintl && ./test.sh
