sudo: false
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    - george-edison55-precise-backports
    # ^ for cmake
    packages:
    - gcc-4.9
    - g++-4.9
    - clang-3.5
    - gettext
    - gdb
    - cmake-data
    - cmake
install:
# set CXX variable
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.5"; fi
# Install Boost headers
  - pwd
  - ls
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

  - BOOST_VER_NUM=57
  - BOOST_DOT_VER_STRING=1.${BOOST_VER_NUM}.0
  - BOOST_UNDERSCORE_VER_STRING=1_${BOOST_VER_NUM}_0

  - BOOST_SUBDIR_NAME=boost_${BOOST_UNDERSCORE_VER_STRING}
  - BOOST_TAR_NAME=${BOOST_SUBDIR_NAME}.tar.gz

  - BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_DOT_VER_STRING}/${BOOST_TAR_NAME}"
  - travis_retry wget ${BOOST_URL}
  - tar -xzf ${BOOST_TAR_NAME}

  - BOOST_DIR_NAME=${DEPS_DIR}/${BOOST_SUBDIR_NAME}

  - pwd
  - ls
  - cd ..

  - pwd
  - ls
  - if [[   -d ${BOOST_DIR_NAME} ]]; then echo "Have boost"; else echo "No boost (?)"; fi
  - if [[   -f ${BOOST_DIR_NAME}/boost/version.hpp ]]; then echo "Have boost version hpp"; else echo "No boost version hpp (?)"; fi

  - CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR_NAME} -DBoost_DEBUG=on"
script:
  - $CXX --version
  - pwd
  - ls

  - echo "Unit Tests"
  - cd test && ./test.sh BOOST_DIR=${BOOST_DIR_NAME}

  - echo "Libintl Validation Tests"
  - cd ../test_libintl && ./test.sh ${CMAKE_OPTIONS}

  - echo "SPIRIT_PO_NOEXCEPT build"
  - ./test.sh -DNOEXCEPT=1 ${CMAKE_OPTIONS}

  - echo "SPIRIT_PO_DEBUG build"
  - ./test.sh -DDEBUG=1 ${CMAKE_OPTIONS}

  - echo "SPIRIT_PO_NOEXCEPT + SPIRIT_PO_DEBUG build"
  - ./test.sh -DNOEXCEPT=1 -DDEBUG=1 ${CMAKE_OPTIONS}
