sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - ppa:boost-latest/ppa
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
    - gettext
    - libintl-dev
    - libboost-all-dev
script:
  - cd test && ./test.sh
  - cd ..
  - cd test_libintl && ./test.sh
