sudo: false
language: cpp

env:
  global:

  # Workaround for https://github.com/travis-ci/travis-ci/issues/4681
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    packages:
      - g++-4.9 # This is needed only to get a >= 4.7 version of libstdc++,
                # clang will fail to build without it
      - libgmp-dev # These are gcc dependencies
      - libmpfr-dev
      - libmpc-dev
    sources:
      - ubuntu-toolchain-r-test

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

env: COMPILER=g++-4.9 BOOST_VER_NUM=48

matrix:
  include:
    - env: GCC_VERSION=4.9.3 BOOST_VER_NUM=48
      compiler: gcc
    - env: GCC_VERSION=4.9.3 BOOST_VER_NUM=51
      compiler: gcc
    - env: GCC_VERSION=4.9.3 BOOST_VER_NUM=54
      compiler: gcc
    - env: GCC_VERSION=4.9.3 BOOST_VER_NUM=57
      compiler: gcc
    - env: GCC_VERSION=4.9.3 BOOST_VER_NUM=60
      compiler: gcc

    - env: GCC_VERSION=5.3.0 BOOST_VER_NUM=48
      compiler: gcc
    - env: GCC_VERSION=5.3.0 BOOST_VER_NUM=51
      compiler: gcc
    - env: GCC_VERSION=5.3.0 BOOST_VER_NUM=54
      compiler: gcc
    - env: GCC_VERSION=5.3.0 BOOST_VER_NUM=57
      compiler: gcc
    - env: GCC_VERSION=5.3.0 BOOST_VER_NUM=60
      compiler: gcc

    - env: LLVM_VERSION=3.5.0 BOOST_VER_NUM=48
      compiler: clang
    - env: LLVM_VERSION=3.5.0 BOOST_VER_NUM=51
      compiler: clang
    - env: LLVM_VERSION=3.5.0 BOOST_VER_NUM=54
      compiler: clang
    - env: LLVM_VERSION=3.5.0 BOOST_VER_NUM=57
      compiler: clang
    - env: LLVM_VERSION=3.5.0 BOOST_VER_NUM=60
      compiler: clang

    - env: LLVM_VERSION=3.7.0 BOOST_VER_NUM=57
      compiler: clang
    - env: LLVM_VERSION=3.7.0 BOOST_VER_NUM=58
      compiler: clang
    - env: LLVM_VERSION=3.8.0 BOOST_VER_NUM=59
      compiler: clang
    - env: LLVM_VERSION=3.8.0 BOOST_VER_NUM=60
      compiler: clang


before_install:
  - export BOOST_VERSION=1.${BOOST_VER_NUM}.0

install:
  - wget https://raw.githubusercontent.com/cbeck88/travis-cpp-assistant/master/install.sh
  - chmod +x install.sh
  - travis_wait 50 source ./install.sh

  - export CXX_FLAGS_BASE="-O3 -Wall -Werror"
  - CXX_FLAGS_BASE+="${CXXFLAGS}"
  - export CXX_FLAGS_NOEXCEPT="${CXX_FLAGS_BASE}"
  - if [ $BOOST_VER_NUM -ge 55 ]; then export CXX_FLAGS_NOEXCEPT+=" -fno-exceptions"; fi

  - CMAKE_OPTIONS=" -DBOOST_ROOT=${BOOST_ROOT}"
  - cd ${TRAVIS_BUILD_DIR}

script:
  - $CXX --version

  - echo "Unit Tests"
  - cd test
  - ./test.sh BOOST_DIR=${BOOST_DIR_NAME}

  - echo "Libintl Validation Tests" && export CXXFLAGS=${CXX_FLAGS_BASE}
  - cd ../test_libintl
  - ./test.sh ${CMAKE_OPTIONS}

  - echo "SPIRIT_PO_NOEXCEPT build" && export CXXFLAGS=${CXX_FLAGS_NOEXCEPT}
  - ./test.sh -DNOEXCEPT=1 ${CMAKE_OPTIONS}

  - echo "SPIRIT_PO_DEBUG build" && export CXXFLAGS=${CXX_FLAGS_BASE}
  - ./test.sh -DDEBUG=1 ${CMAKE_OPTIONS}

  - echo "SPIRIT_PO_NOEXCEPT + SPIRIT_PO_DEBUG build" && export CXXFLAGS=${CXX_FLAGS_NOEXCEPT}
  - ./test.sh -DNOEXCEPT=1 -DDEBUG=1 ${CMAKE_OPTIONS}
