sudo: false
language: cpp
compiler:
  - gcc
  - clang
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    - george-edison55-precise-backports
    # - kubuntu-backports
    # ^ for cmake
    packages:
    - gcc-4.9
    - g++-4.9
    - clang
    - clang++
    - gettext
    - libintl-dev
#    - libboost-all-dev
    - libboost1.55-all-dev
    - gdb
    - cmake
script:
  - cd test && ./test.sh
  - cd ..
  - cd test_libintl && ./test.sh
